spring:
  application:
    name: "The Game"
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "rootroot"


server:
  ssl:
    enabled: true
    key-store-type: "PKCS12"
    key-store: "classpath:ssl/game_ssl.p12"
    key-store-password: "rootroot"
  port: 4321
